export const  Detail=[
    {  "id" : "1"  ,
        "title":"MACTREM ST46 Selfie Stick Camera Stand Tripod For Smart Mobile Phone Camera",
        "des":"MACTREM ST46 Lightweight Aluminum Alloy Selfie Stick Camera Stand Tripod For Smart Mobile Phone Camera officiaL PRICE 5873",
        "imgurl":"https://savoy.nordicmade.com/wp-content/uploads/2015/08/product-classic-chair-2-300x372.jpg",
        "price":"3500",
        "deleteprice":"5000"
    },
    {  "id" : "2"  ,
        "title":"Chang WallLight Indoor 1Pcs Up Down Wall Light",
        "des":"ChangM Wall Lights Indoor 1Pcs Up Down Wall Light 16W 3000K Modern Style Aluminum LED Wall Lamps,Perfect for Bedroom Living Room Hallway Corridor Stairs Warm White ",
        "imgurl":"https://m.media-amazon.com/images/I/61Zz8NoXBmL._AC_UF1000,1000_QL80_.jpg",
        "price":"5000",
    },
    {  "id" :  "3" ,
        "title":"ATUMTEK Bluetooth Selfie Stick Tripod",
        "des":"ATUMTEK Bluetooth Selfie Stick Tripod, Extendable 3 in 1 Aluminum Selfie Stick with Wireless Remote and Tripod Stand 270 Rotation for iPhone 13/12/11 Pro/XS Max/XS/XR/X, Samsung and Smartphone Black",
        "imgurl":":https://web.whatsapp.com/0a17a037-4724-403a-b8f5-55a537a3517c",
        "price":"5000",
    },
    {  "id" : "4"  ,
        "title":"Svarog 2 Packs LED String Lights ",
        "des":"Svarog 2 Packs LED String Lights with Remote Control Battery Operated Fairy String Lights,16ft 50LED Waterproof Copper Wire Starry Fairy Light",
        "imgurl":"blob:https://web.whatsapp.com/c629876f-9ffb-4e56-a8f5-f1da70dd04e0",
        "price":"2500",
    },
    {  "id" :  "5" ,
    "title":"seacosmo 3in1 Wireless Charger for Samsung Galaxy Watch 5 Pro/4/3/2/1, Charging Station for Samsung Note/S/Z Series and iPhone Qi-Certified Phones",
    "des":"seacosmo 3 in 1 Wireless Charger for Samsung Galaxy Watch 5 Pro/4/3/2/1, Charging Station for Samsung Note/S/Z Series and iPhone Qi-Certified Phones, Charging Dock for Galaxy Buds(Not for iWatch)",
    "imgurl":"", cat : "",
    "price":"8000",
    "deleteprice":"14000",
    },
    {  "id" : "6"  ,
      "title":"MAS Carney TI3 Wired USB Type C Headphones, USB C Earbuds, Earphones with Microphone",
      "des":"Brand	MAS CARNEYForm factor	In Ear Connectivity technology	Wired Wireless communication technology	Bluetooth Special feature	Ergonomic, Lightweight, Microphone Included",
      "imgurl":"", cat : "",
      "price":"3200","deleteprice":"5300",
      },
      {  "id" : "8"  ,
        "title":"g pro wireless PC Joystick Controller For Nintendo Game",
        "des":"official price Rs.5000 g pro wireless PC Joystick Controller For Nintendo Game Brand Magic Model Number	 SD-17 Colour	 RED(L)+BLUE(R),BLUE(L)+RED(R) Compatible Platform	 Nintendo/Switch/PC Product size	 15*10.6*5.5cm Connect Type	 Bluetooth/Usb connection Battery capacity	 600mAh Type	 Wireless joystick",
        "imgurl":"", cat : "cameraAccosiries",
        "price":"3500","deleteprice":"",
        },
        {  "id" :  "9" ,
          "title":"Sansnail Mini Camera 1080P Hidden Camera SQ11 Portable Small HD Nanny Cam with Night Vision and Motion Detection Indoor Covert Security Camera",
          "des":"Sansnail Mini Spy Camera 1080P Hidden Camera SQ11 Portable Small HD Nanny Cam with Night Vision and Motion Detection Indoor Covert Security Camera for Home and Office Hidden Spy Cam Recommended Uses For Product	Spy,Indoor,Outdoor Brand	Sansnail Model Name	Mini Hidden camera Connectivity Technology	Wired Special Feature	1080P, Mini camera, Hidden camera, Spy camera, Cam",
          "imgurl":"", cat : "cameraAccosiries",
          "price":"3500","deleteprice":"3965",
          },
          {  "id" :  "10" ,
            "title":"64 GB Clip MP3 Player, ZOOAOXO Music Player with Bluetooth 5.2, HD Screen, HiFi Sound, Voice Recorder, FM Radio, Pedometer,",
            "des":"64 GB Clip MP3 Player, ZOOAOXO Music Player with Bluetooth 5.2, HD Screen, HiFi Sound, Voice Recorder, FM Radio, Pedometer, 1.04 oz Ultra-Light, Great for Sports, Card Reader and Earphones Included            ",
            "imgurl":"", cat : "cameraAccosiries",
            "price":"3500","deleteprice":"7350",
            },
            {  "id" : "11"  ,
              "title":"OASO Stylus Pen for Touch Screens, Disc Tip & Magnet Cap Styli Pencil Compatible All Touch Devices",
              "des":"Color	WHITe  Brand	OASO Material	Aluminum Compatible Devices	Tablet Item Dimensions LxWxH	6.3 x 3.54 x 0.39 inches Are Batteries Included	No Batteries Required?	No",
              "imgurl":"", cat : "",
              "price":"2000","deleteprice":"3081",
              },
              {  "id" : "12"  ,
                "title":"SONOFF DUALR3 Lite Smart Switch Moudle WiFi Smart Curtain Switch,Dual Relay DIY Curtain,Compatible with Alexa&Google Assistant(1 Pack)",
                "des":"SONOFF DUALR3 Lite Smart Switch Moudle,WiFi Smart Curtain Switch,Dual Relay DIY Curtain, Blinds, Roller Shutter,Two Way Smart Switch,Compatible with Alexa&Google Assistant(1 Pac ",
                "imgurl":"", cat : "",
                "price":"3500","deleteprice":"5200",
                },
                {  "id" : "13"  ,
                  "title":"beler 2pcs 12V Gold Universal Positive & Negative 2 4 8 Gauge AWG Car Battery Terminal Clamp Connector with Plastic Cover",
                  "des":"Note: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.",
                  "imgurl":"", cat : "",
                  "price":"3000","deleteprice":"4800",
                  },
                  // {  "id" :   ,
                  //   "title":"",
                  //   "des":"",
                  //   "imgurl":"", cat : "",
                  //   "price":"","deleteprice":"",
                  //   }
   ]